server:
  port: 8081
spring:
  application:
   name: service-by-suyog
  datasource:
    url: jdbc:mysql://localhost:3306/student_curd?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 6
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      enable_lazy_load_no_trans: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB